//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.09 at 02:13:46 AM CEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for soba complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="soba">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idSobe" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="brojSobe" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="brojKreveta" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "soba", propOrder = {
    "idSobe",
    "brojSobe",
    "brojKreveta"
})
public class Soba {

    protected long idSobe;
    protected int brojSobe;
    protected int brojKreveta;

    /**
     * Gets the value of the idSobe property.
     * 
     */
    public long getIdSobe() {
        return idSobe;
    }

    /**
     * Sets the value of the idSobe property.
     * 
     */
    public void setIdSobe(long value) {
        this.idSobe = value;
    }

    /**
     * Gets the value of the brojSobe property.
     * 
     */
    public int getBrojSobe() {
        return brojSobe;
    }

    /**
     * Sets the value of the brojSobe property.
     * 
     */
    public void setBrojSobe(int value) {
        this.brojSobe = value;
    }

    /**
     * Gets the value of the brojKreveta property.
     * 
     */
    public int getBrojKreveta() {
        return brojKreveta;
    }

    /**
     * Sets the value of the brojKreveta property.
     * 
     */
    public void setBrojKreveta(int value) {
        this.brojKreveta = value;
    }

}
