//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 08:09:59 PM CEST 
//


package tim23.hotelservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id_cene" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Pocetak_vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Kraj_vazenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Vrednost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idCene",
    "pocetakVazenja",
    "krajVazenja",
    "vrednost"
})
@XmlRootElement(name = "Cena")
public class Cena {

    @XmlElement(name = "Id_cene")
    protected int idCene;
    @XmlElement(name = "Pocetak_vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar pocetakVazenja;
    @XmlElement(name = "Kraj_vazenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar krajVazenja;
    @XmlElement(name = "Vrednost")
    protected double vrednost;

    /**
     * Gets the value of the idCene property.
     * 
     */
    public int getIdCene() {
        return idCene;
    }

    /**
     * Sets the value of the idCene property.
     * 
     */
    public void setIdCene(int value) {
        this.idCene = value;
    }

    /**
     * Gets the value of the pocetakVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPocetakVazenja() {
        return pocetakVazenja;
    }

    /**
     * Sets the value of the pocetakVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPocetakVazenja(XMLGregorianCalendar value) {
        this.pocetakVazenja = value;
    }

    /**
     * Gets the value of the krajVazenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKrajVazenja() {
        return krajVazenja;
    }

    /**
     * Sets the value of the krajVazenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKrajVazenja(XMLGregorianCalendar value) {
        this.krajVazenja = value;
    }

    /**
     * Gets the value of the vrednost property.
     * 
     */
    public double getVrednost() {
        return vrednost;
    }

    /**
     * Sets the value of the vrednost property.
     * 
     */
    public void setVrednost(double value) {
        this.vrednost = value;
    }

}
