//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 08:09:59 PM CEST 
//


package tim23.hotelservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id_poruka" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Id_posiljaoca" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Id_primaoca" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Tip_posiljaoca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tip_primaoca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sadrzaj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idPoruka",
    "idPosiljaoca",
    "idPrimaoca",
    "tipPosiljaoca",
    "tipPrimaoca",
    "sadrzaj"
})
@XmlRootElement(name = "Poruka")
public class Poruka {

    @XmlElement(name = "Id_poruka")
    protected int idPoruka;
    @XmlElement(name = "Id_posiljaoca")
    protected int idPosiljaoca;
    @XmlElement(name = "Id_primaoca")
    protected int idPrimaoca;
    @XmlElement(name = "Tip_posiljaoca", required = true)
    protected String tipPosiljaoca;
    @XmlElement(name = "Tip_primaoca", required = true)
    protected String tipPrimaoca;
    @XmlElement(name = "Sadrzaj", required = true)
    protected String sadrzaj;

    /**
     * Gets the value of the idPoruka property.
     * 
     */
    public int getIdPoruka() {
        return idPoruka;
    }

    /**
     * Sets the value of the idPoruka property.
     * 
     */
    public void setIdPoruka(int value) {
        this.idPoruka = value;
    }

    /**
     * Gets the value of the idPosiljaoca property.
     * 
     */
    public int getIdPosiljaoca() {
        return idPosiljaoca;
    }

    /**
     * Sets the value of the idPosiljaoca property.
     * 
     */
    public void setIdPosiljaoca(int value) {
        this.idPosiljaoca = value;
    }

    /**
     * Gets the value of the idPrimaoca property.
     * 
     */
    public int getIdPrimaoca() {
        return idPrimaoca;
    }

    /**
     * Sets the value of the idPrimaoca property.
     * 
     */
    public void setIdPrimaoca(int value) {
        this.idPrimaoca = value;
    }

    /**
     * Gets the value of the tipPosiljaoca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipPosiljaoca() {
        return tipPosiljaoca;
    }

    /**
     * Sets the value of the tipPosiljaoca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipPosiljaoca(String value) {
        this.tipPosiljaoca = value;
    }

    /**
     * Gets the value of the tipPrimaoca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipPrimaoca() {
        return tipPrimaoca;
    }

    /**
     * Sets the value of the tipPrimaoca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipPrimaoca(String value) {
        this.tipPrimaoca = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSadrzaj(String value) {
        this.sadrzaj = value;
    }

}
