//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.09 at 12:38:08 AM CEST 
//


package rs.ac.uns.ftn.poruke;

import javax.xml.bind.annotation.XmlRegistry;

import rs.ac.uns.ftn.entiteti.Adresa;
import rs.ac.uns.ftn.entiteti.Soba;
import rs.ac.uns.ftn.korisnik.Administrator;
import rs.ac.uns.ftn.korisnik.Agent;
import rs.ac.uns.ftn.korisnik.KrajnjiKorisnik;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.poruke package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.poruke
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ponuda }
     * 
     */
    public Ponuda createPonuda() {
        return new Ponuda();
    }

    /**
     * Create an instance of {@link Soba }
     * 
     */
    public Soba createSoba() {
        return new Soba();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link OcenaSmestaja }
     * 
     */
    public OcenaSmestaja createOcenaSmestaja() {
        return new OcenaSmestaja();
    }

    /**
     * Create an instance of {@link KrajnjiKorisnik }
     * 
     */
    public KrajnjiKorisnik createKrajnjiKorisnik() {
        return new KrajnjiKorisnik();
    }

    /**
     * Create an instance of {@link PostavljanjeKomentara }
     * 
     */
    public PostavljanjeKomentara createPostavljanjeKomentara() {
        return new PostavljanjeKomentara();
    }

    /**
     * Create an instance of {@link GetSobaRequest }
     * 
     */
    public GetSobaRequest createGetSobaRequest() {
        return new GetSobaRequest();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link PostavljanjeSmestaja }
     * 
     */
    public PostavljanjeSmestaja createPostavljanjeSmestaja() {
        return new PostavljanjeSmestaja();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Administrator }
     * 
     */
    public Administrator createAdministrator() {
        return new Administrator();
    }

}
