//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 08:16:54 PM CEST 
//


package tim23.adminservice.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id_komentara" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sadrzaj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Odobreno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idKomentara",
    "sadrzaj",
    "odobreno"
})
@XmlRootElement(name = "Komentar")
@Entity
public class Komentar {

    @XmlElement(name = "Id_komentara", required = true)
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Integer idKomentara;
    
    @XmlElement(name = "Sadrzaj", required = true)
    @Column
    private String sadrzaj;
    
    @XmlElement(name="Smestaj", required = true)
    @OneToOne
    @JoinColumn(name = "id_smestaja")
    private Rezervacija rezervacija;
    
    @XmlElement(name = "Datum_komentara", required = true)
    @XmlSchemaType(name = "date")
    @Column
    private Date datumKomentara;
    
    @XmlElement(name = "Odobreno")
    @Column
    private Boolean odobreno;

    /**
     * Gets the value of the idKomentara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getIdKomentara() {
        return idKomentara;
    }

    /**
     * Sets the value of the idKomentara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdKomentara(Integer value) {
        this.idKomentara = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSadrzaj(String value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the odobreno property.
     * 
     */
    public Boolean isOdobreno() {
        return odobreno;
    }

    /**
     * Sets the value of the odobreno property.
     * 
     */
    public void setOdobreno(Boolean value) {
        this.odobreno = value;
    }

}
