//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.26 at 06:32:54 PM CEST 
//


package rs.ac.uns.ftn.korisnik;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.korisnik package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Administrator_QNAME = new QName("http://www.ftn.uns.ac.rs/korisnik", "Administrator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.korisnik
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link KrajnjiKorisnik }
     * 
     */
    public KrajnjiKorisnik createKrajnjiKorisnik() {
        return new KrajnjiKorisnik();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TKorisnik }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/korisnik", name = "Administrator")
    public JAXBElement<TKorisnik> createAdministrator(TKorisnik value) {
        return new JAXBElement<TKorisnik>(_Administrator_QNAME, TKorisnik.class, null, value);
    }

}
