//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 08:11:45 PM CEST 
//


package tim23.hotelservice.model.poruke;

import javax.xml.bind.annotation.XmlRegistry;

//import tim23.hotelservice.model.Agent;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tim23.hotelservice.model.poruke package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tim23.hotelservice.model.poruke
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAgentRequest }
     * 
     */
    public GetAgentRequest createGetAgentRequest() {
        return new GetAgentRequest();
    }

    /**
     * Create an instance of {@link GetAgentResponse }
     * 
     */
    public GetAgentResponse createGetAgentResponse() {
        return new GetAgentResponse();
    }
    
    public GetAgentListRequest createGetAgentListRequest() {
    	return new GetAgentListRequest();
    }
    
    public GetAgentListResponse createGetAgentListResponse() {
    	return new GetAgentListResponse();
    }
    
    public GetReservationListRequest createGetReservationListRequest() {
    	return new GetReservationListRequest();
    }
    
    public GetReservationListResponse createGetReservationListResponse() {
    	return new GetReservationListResponse();
    }
    
    public GetSobaRequest createGetSobaRequest() {
    	return new GetSobaRequest();
    }
    
    public GetSobaResponse createGetSobaResonse() {
    	return new GetSobaResponse();
    }
    
    public GetAdresaListRequest createGetAdresaListRequest() {
    	return new GetAdresaListRequest();
    }
    
    public GetAdresaListResponse createGetAdresaListResonse() {
    	return new GetAdresaListResponse();
    }
    
    public GetTipSmestajaListRequest createGetTipoviSmestajaListRequest() {
    	return new GetTipSmestajaListRequest();
    }
    
    public GetTipSmestajaListResponse createGetTipSmestajaListResponse() {
    	return new GetTipSmestajaListResponse();
    }
    
    public GetDodatneUslugeListRequest createDodatneUslugeListRequest() {
    	return new GetDodatneUslugeListRequest();
    }
    
    public GetDodatneUslugeListResponse createDodatneUslugeListResponse() {
    	return new GetDodatneUslugeListResponse();
    }
    
    public GetSobaDodatnaUslugaRequest createGetSobaDodatnaUslugaRequest() {
    	return new GetSobaDodatnaUslugaRequest();
    }
    
    public GetSobaDodatnaUslugaResponse createGetSobaDodatnaUslugaResponse() {
    	return new GetSobaDodatnaUslugaResponse();
    }
    
    public GetCenaRequest createGetCenaRequest() {
    	return new GetCenaRequest();
    }
    
    public GetCenaResponse createGetCenaResponse() {
    	return new GetCenaResponse();
    }
    
    /**
     * Create an instance of {@link Agent }
     * 
     */
//    public Agent createAgent() {
//        return new Agent();
//    }
}
