//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 08:16:54 PM CEST 
//


package tim23.agent.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id_rezervacije" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Datum_dolaska" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Datum_odlaska" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Broj_osoba" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Id_sobe" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/entiteti}Krajnji_korisnik" minOccurs="0"/>
 *         &lt;element name="Realizovana" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Ocena" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/entiteti}Komentar" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idRezervacije",
    "datumDolaska",
    "datumOdlaska",
    "brojOsoba",
    "idSobe",
    "krajnjiKorisnik",
    "realizovana",
    "ocena",
    "komentar"
})
@XmlRootElement(name = "Rezervacija")
public class Rezervacija {

    @XmlElement(name = "Id_rezervacije")
    protected long idRezervacije;
    @XmlElement(name = "Datum_dolaska", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDolaska;
    @XmlElement(name = "Datum_odlaska", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumOdlaska;
    @XmlElement(name = "Broj_osoba")
    protected Integer brojOsoba;
    @XmlElement(name = "Id_sobe")
    protected int idSobe;
    @XmlElement(name = "Krajnji_korisnik")
    protected KrajnjiKorisnik krajnjiKorisnik;
    @XmlElement(name = "Realizovana")
    protected boolean realizovana;
    @XmlElement(name = "Ocena")
    protected Double ocena;
    @XmlElement(name = "Komentar")
    protected Komentar komentar;

    /**
     * Gets the value of the idRezervacije property.
     * 
     */
    public long getIdRezervacije() {
        return idRezervacije;
    }

    /**
     * Sets the value of the idRezervacije property.
     * 
     */
    public void setIdRezervacije(long value) {
        this.idRezervacije = value;
    }

    /**
     * Gets the value of the datumDolaska property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDolaska() {
        return datumDolaska;
    }

    /**
     * Sets the value of the datumDolaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDolaska(XMLGregorianCalendar value) {
        this.datumDolaska = value;
    }

    /**
     * Gets the value of the datumOdlaska property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumOdlaska() {
        return datumOdlaska;
    }

    /**
     * Sets the value of the datumOdlaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumOdlaska(XMLGregorianCalendar value) {
        this.datumOdlaska = value;
    }

    /**
     * Gets the value of the brojOsoba property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojOsoba() {
        return brojOsoba;
    }

    /**
     * Sets the value of the brojOsoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojOsoba(Integer value) {
        this.brojOsoba = value;
    }

    /**
     * Gets the value of the idSobe property.
     * 
     */
    public int getIdSobe() {
        return idSobe;
    }

    /**
     * Sets the value of the idSobe property.
     * 
     */
    public void setIdSobe(int value) {
        this.idSobe = value;
    }

    /**
     * Gets the value of the krajnjiKorisnik property.
     * 
     * @return
     *     possible object is
     *     {@link KrajnjiKorisnik }
     *     
     */
    public KrajnjiKorisnik getKrajnjiKorisnik() {
        return krajnjiKorisnik;
    }

    /**
     * Sets the value of the krajnjiKorisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link KrajnjiKorisnik }
     *     
     */
    public void setKrajnjiKorisnik(KrajnjiKorisnik value) {
        this.krajnjiKorisnik = value;
    }

    /**
     * Gets the value of the realizovana property.
     * 
     */
    public boolean isRealizovana() {
        return realizovana;
    }

    /**
     * Sets the value of the realizovana property.
     * 
     */
    public void setRealizovana(boolean value) {
        this.realizovana = value;
    }

    /**
     * Gets the value of the ocena property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOcena() {
        return ocena;
    }

    /**
     * Sets the value of the ocena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOcena(Double value) {
        this.ocena = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link Komentar }
     *     
     */
    public Komentar getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Komentar }
     *     
     */
    public void setKomentar(Komentar value) {
        this.komentar = value;
    }

}
